import Images from '../../constants/images';

export default [
    {
        "id": 1,
        "name": "Janique costa",
        "gender": "male",
        "image": Images.maleImage,
        "email": "janiuqe.costa@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "London",
    },
    {
        "id": 2,
        "name": "afsar kavakhioglu",
        "gender": "female",
        "image": Images.femaleImage,
        "email": "afsar.kavakoglu@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "London",
    },
    {
        "id": 3,
        "name": "eva duncan",
        "gender": "female",
        "image": Images.femaleImage,
        "email": "eva.duncan@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "Washington",
    },
    {
        "id": 4,
        "name": "jennifer fowler",
        "gender": "female",
        "image": Images.femaleImage,
        "email": "jennifer.fowler@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "Washington",
    },

    {
        "id": 5,
        "name": "William blanc",
        "gender": "male",
        "image": Images.maleImage,
        "email": "william.blanc@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "Washington",
    },

    {
        "id": 6,
        "name": "inja lampi",
        "gender": "male",
        "image": Images.maleImage,
        "email": "pinja.lampi@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "Washington",
    },

    {
        "id": 7,
        "name": "Evelyn Lyons",
        "gender": "female",
        "image": Images.femaleImage,
        "email": "evelyn.lyons@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "London",
    },

    {
        "id": 8,
        "name": "Wilfredo Kelley",
        "gender": "male",
        "image": Images.maleImage,
        "email": "willfredo.kelley@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "Washington",
    },
    {
        "id": 9,
        "name": "Jimmie Nicolas",
        "gender": "male",
        "image": Images.maleImage,
        "email": "jimmie.nicolas@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "London",
    },
    {
        "id": 10,
        "name": "Darrel Mota",
        "gender": "male",
        "image": Images.maleImage,
        "email": "darrel.mota@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "London",
    },
    {
        "id": 11,
        "name": "Alfred Lucero",
        "gender": "male",
        "image": Images.maleImage,
        "email": "alfred.lucero@gmail.com",
        "created_at": "2019-02-08T15:59:30.947445Z",
        "position": "London",
    },
]